<?php

use Detain\MyAdminVestaCP\VestaCP;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-26 at 07:58:15.
 */
class VestaCPTest extends TestCase
{
	/**
	 * @var VestaCP
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new VestaCP;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Detain\MyAdminVestaCP\VestaCP::createAccount
	 * @todo   Implement testCreateAccount().
	 */
	public function testCreateAccount()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminVestaCP\VestaCP::addWebDnsMailDomain
	 * @todo   Implement testAddWebDnsMailDomain().
	 */
	public function testAddWebDnsMailDomain()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminVestaCP\VestaCP::addDatabase
	 * @todo   Implement testAddDatabase().
	 */
	public function testAddDatabase()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminVestaCP\VestaCP::listAccount
	 * @todo   Implement testListAccount().
	 */
	public function testListAccount()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminVestaCP\VestaCP::listWebDomains
	 * @todo   Implement testListWebDomains().
	 */
	public function testListWebDomains()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminVestaCP\VestaCP::deleteAccount
	 * @todo   Implement testDeleteAccount().
	 */
	public function testDeleteAccount()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminVestaCP\VestaCP::suspendAccount
	 * @todo   Implement testSuspendAccount().
	 */
	public function testSuspendAccount()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminVestaCP\VestaCP::unsuspendAccount
	 * @todo   Implement testUnsuspendAccount().
	 */
	public function testUnsuspendAccount()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminVestaCP\VestaCP::checkUserPass
	 * @todo   Implement testCheckUserPass().
	 */
	public function testCheckUserPass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminVestaCP\VestaCP::setHostname
	 * @todo   Implement testSetHostname().
	 */
	public function testSetHostname()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminVestaCP\VestaCP::setPassword
	 * @todo   Implement testSetPassword().
	 */
	public function testSetPassword()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminVestaCP\VestaCP::setUsername
	 * @todo   Implement testSetUsername().
	 */
	public function testSetUsername()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminVestaCP\VestaCP::getResponse
	 * @todo   Implement testGetResponse().
	 */
	public function testGetResponse()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
